# Configuration file
seed: 173
model_name: 'seq2seq_00'

# DATA
val_size: 0.1

# MODEL
# # Set model type: 1: 'multi step RNN'; 2: 'seq2seq'
model_type: 2
len_input: 128
len_prediction: 28
lstm_size: 64

# TRAINING
learning_rate: 0.0001
n_epochs: 1
batch_size: 64
shuffle: True
use_gpu: 5632 #True
