# Configuration file
'seed': 173


# DATAPREP
# val_test_len
'placeholder': -0.1


# MODEL
'lstm_size': 200
'conv_filters': [8, 16]
'conv_activation': 'elu'
'use_batchnorm': True
'decoder_hidden_size': 200

# TRAINING
'learning_rate': 0.0001
'n_epochs': 15
'batch_size': 128
'shuffle': True
